const branches=[['center','Cosmo Center','08:00-22:00'],['park','Cosmo Park','09:00-23:00'],['express','Cosmo Express','07:30-21:00']];
const items=[['latte','coffee','☕','Salted Caramel Latte','espresso, milk, caramel',190],['americano','coffee','☕','Americano','classic black coffee',120],['cappuccino','coffee','☕','Cappuccino','espresso and milk foam',160],['raf','coffee','☕','Vanilla Raf','cream, vanilla, espresso',210],['matcha','special','🍵','Iced Matcha','matcha, milk, ice',220],['coldbrew','special','🫐','Berry Cold Brew','cold brew and berry foam',240],['croissant','food','🥐','Butter Croissant','warm pastry',95],['cake','food','🍰','Basque Cheesecake','creamy dessert',180],['tiramisu','food','🍫','Coffee Tiramisu','coffee cream dessert',210]];
const cats=[['all','Все'],['coffee','Кофе'],['special','Special'],['food','Десерты']];
let cat='all';let branch='center';let cart=[];
const el=id=>document.getElementById(id);const som=n=>n+' сом';
function button(txt,fn){const b=document.createElement('button');b.textContent=txt;b.onclick=fn;return b;}
function renderBranches(){const root=el('branchTabs');root.textContent='';branches.forEach(b=>{const btn=button(b[1]+' · '+b[2],()=>{branch=b[0];renderBranches();});if(b[0]===branch)btn.className='active';root.appendChild(btn);});const sel=el('orderBranch');sel.textContent='';branches.forEach(b=>{const o=document.createElement('option');o.value=b[0];o.textContent=b[1];sel.appendChild(o);});sel.value=branch;sel.onchange=()=>{branch=sel.value;renderBranches();};}
function renderCats(){const root=el('categoryTabs');root.textContent='';cats.forEach(c=>{const btn=button(c[1],()=>{cat=c[0];renderCats();renderMenu();});if(c[0]===cat)btn.className='active';root.appendChild(btn);});}
function add(id){const line=cart.find(x=>x.id===id);if(line)line.qty++;else cart.push({id,qty:1});renderCart();el('cart').classList.add('open');}
function renderMenu(){const root=el('menuGrid');root.textContent='';items.filter(i=>cat==='all'||i[1]===cat).forEach(i=>{const card=document.createElement('article');card.className='menu-card';const pic=document.createElement('div');pic.className='pic';pic.textContent=i[2];const h=document.createElement('h3');h.textContent=i[3];const p=document.createElement('p');p.textContent=i[4];const f=document.createElement('footer');const price=document.createElement('b');price.textContent=som(i[5]);f.append(price,button('+',()=>add(i[0])));card.append(pic,h,p,f);root.appendChild(card);});}
function renderCart(){el('cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);const root=el('cartItems');root.textContent='';let total=0;if(!cart.length){root.textContent='Корзина пустая.';el('cartTotal').textContent=som(0);return;}cart.forEach(line=>{const i=items.find(x=>x[0]===line.id);total+=i[5]*line.qty;const row=document.createElement('div');row.className='cartItem';const name=document.createElement('span');name.textContent=i[3]+' × '+line.qty;const controls=document.createElement('span');controls.append(button('-',()=>{line.qty--;if(line.qty<1)cart=cart.filter(x=>x.id!==line.id);renderCart();}),button('+',()=>{line.qty++;renderCart();}));row.append(name,controls);root.appendChild(row);});const promo=el('promoInput').value.trim().toUpperCase();if(promo==='COSMO10')total=Math.round(total*.9);el('cartTotal').textContent=som(total);}
function copyOrder(){const b=branches.find(x=>x[0]===branch);let total=el('cartTotal').textContent;let text='Cosmo Social Coffee demo\nФилиал: '+b[1]+'\n';cart.forEach(line=>{const i=items.find(x=>x[0]===line.id);text+='\n- '+i[3]+' × '+line.qty;});text+='\n\nИтого: '+total;el('status').textContent=text;}
el('openCart').onclick=()=>el('cart').classList.add('open');el('closeCart').onclick=()=>el('cart').classList.remove('open');el('promoInput').oninput=renderCart;el('copyOrder').onclick=copyOrder;renderBranches();renderCats();renderMenu();renderCart();
